### ISSUE TITLE
node-總追蹤

### ISSUE THREAD

**Issue by sharonyu0823** [sharonyu0823/no_waste_.sybackup#17]
https://docs.google.com/spreadsheets/d/1EsuY0eAEYbnuIoFrApEbLUUVgNjrxy_fOgw6nPikkOU/edit#gid=587329884

**Comment by sharonyu0823** [comment]
- [x] [node-註冊](https://github.com/sharonyu0823/no_waste_.sybackup/issues/14)
- [x] [node-註冊帳號重複](https://github.com/sharonyu0823/no_waste_.sybackup/issues/15)
- [x] [node-登入](https://github.com/sharonyu0823/no_waste_.sybackup/issues/16)
- [ ] [node-忘記密碼](https://github.com/sharonyu0823/no_waste_.sybackup/issues/18)
- [ ] [node-個人資料(讀取)](https://github.com/sharonyu0823/no_waste_.sybackup/issues/19)
- [ ] [node-個人資料(編輯)](https://github.com/sharonyu0823/no_waste_.sybackup/issues/20)
- [ ] [node-忘記密碼(更新密碼)](https://github.com/sharonyu0823/no_waste_.sybackup/issues/22)
- [ ] [node-刪除帳號](https://github.com/sharonyu0823/no_waste_.sybackup/issues/21)
