### ISSUE TITLE
react-總追蹤

### ISSUE THREAD

**Issue by sharonyu0823** [sharonyu0823/no_waste_.sybackup#23]

**Comment by sharonyu0823** [comment]
- [ ] [react-註冊](https://github.com/sharonyu0823/no_waste_.sybackup/issues/24)
- [ ] [react-註冊帳號重複](https://github.com/sharonyu0823/no_waste_.sybackup/issues/25)
- [ ] [react-登入](https://github.com/sharonyu0823/no_waste_.sybackup/issues/31)
- [ ] [react-忘記密碼](https://github.com/sharonyu0823/no_waste_.sybackup/issues/26)
- [ ] [react-忘記密碼(更新密碼)](https://github.com/sharonyu0823/no_waste_.sybackup/issues/27)
- [ ] [react-個人資料(讀取)](https://github.com/sharonyu0823/no_waste_.sybackup/issues/28)
- [ ] [react-個人資料(編輯)](https://github.com/sharonyu0823/no_waste_.sybackup/issues/29)
- [ ] [react-刪除帳號](https://github.com/sharonyu0823/no_waste_.sybackup/issues/30)
